async function runE2E() {
    const baseUrl = 'http://localhost:3000';
    let institutionCookie = '';
    let programId = '';
    let institutionId = '';

    console.log('--- STARTING E2E TEST ---');

    // step 1: Login as Institution
    try {
        const loginRes = await fetch(`${baseUrl}/api/institution/login`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ email: 'director@nillp.ai', password: 'DKMNILLP@5604' })
        });
        if (!loginRes.ok) {
            const errorText = await loginRes.text();
            throw new Error(`Login failed with status ${loginRes.status}: ${errorText}`);
        }
        const loginData = await loginRes.json();
        institutionId = loginData.id;

        const setCookie = loginRes.headers.get('set-cookie');
        if (!setCookie) throw new Error('No cookie returned from institute login');

        // Extract institution_refresh cookie which is needed usually
        const cookies = setCookie.split(', ').map(c => c.split(';')[0]);
        institutionCookie = cookies.find(c => c.includes('institution_refresh')) || cookies.join('; ');

        console.log('✅ PASS: Institution Login Success');
    } catch (e) {
        console.error('❌ FAIL: Institution Login:', e);
        return;
    }

    // 2.3 Delete previous test stakeholder if exists to avoid UNIQUE constraint error
    const { Pool } = require('pg');
    require('dotenv').config({ path: '.env.local' });
    const pool = new Pool({ connectionString: process.env.DATABASE_URL });
    const client = await pool.connect();
    try {
        await client.query("DELETE FROM representative_stakeholders WHERE member_id = 'T-STK-001'");
    } catch (e) {
        console.error("Cleanup error:", e);
    } finally {
        client.release();
        pool.end();
    }

    // 3. Create a Stakeholder for this Program to get a valid program ID
    try {
        const progRes = await fetch(`${baseUrl}/api/institution/programs`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Cookie': institutionCookie
            },
            body: JSON.stringify({
                program_name: `E2E Test Program ${Date.now()}`,
                degree: 'B.Tech',
                level: 'UG',
                duration: 4,
                intake: 60,
                academic_year: '2023-2027',
                program_code: `E2E-${Date.now()}`
            })
        });

        if (!progRes.ok) throw new Error(`HTTP ${progRes.status}: ${await progRes.text()}`);
        const data = await progRes.json();
        programId = data.program.id;
        console.log('✅ PASS: Created Test Program ID:', programId);
    } catch (e) {
        console.error('❌ FAIL: Creating Program:', e);
        return;
    }

    // step 3: Create a new Stakeholder
    let newStakeholderId = '';
    try {
        const stRes = await fetch(`${baseUrl}/api/institution/stakeholders`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Cookie': institutionCookie
            },
            body: JSON.stringify({
                program_id: programId,
                member_name: `Test Stakeholder ${Date.now()}`,
                email: `test_${Date.now()}@example.com`,
                organization: 'E2E Test Corp',
                category: 'Alumni'
            })
        });

        const data = await stRes.json();
        if (!stRes.ok) throw new Error(JSON.stringify(data));

        newStakeholderId = data.data.member_id;
        console.log('✅ PASS: Stakeholder Created successfully. Stakeholder ID:', newStakeholderId);
    } catch (e) {
        console.error('❌ FAIL: Creating Stakeholder:', e);
        return;
    }

    // step 4: Test Stakeholder Login with the newly created stakeholder
    try {
        console.log('\\n[TEST] Logging in as newly created Stakeholder...');
        const loginRes = await fetch(`${baseUrl}/api/stakeholder/login`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                institute_id: institutionId,
                program_id: programId,
                stakeholder_id: newStakeholderId,
                stakeholder_password: 'apassword' // the default password generated by the system
            })
        });

        const data = await loginRes.json();
        if (loginRes.ok) {
            console.log('✅ PASS: Stakeholder Logged in successfully! Response data:', data.stakeholder);
        } else {
            console.log('❌ FAIL: Stakeholder Login Failed!', data);
        }
    } catch (e) {
        console.error('❌ FAIL: Stakeholder Login Request:', e);
    }
}

runE2E();
