-- Migration: Fix Auth & Foreign Key Constraint
-- Description: Drops the foreign key constraint from public.institutions referencing auth.users(id)
-- Date: 2026-03-31

BEGIN;

-- 1. Drop the foreign key constraint if it exists
-- Note: 'institutions_id_fkey' is the default name generated by PostgreSQL/Supabase
ALTER TABLE IF EXISTS public.institutions 
  DROP CONSTRAINT IF EXISTS institutions_id_fkey;

-- 2. Ensure 'id' column is just a UUID primary key without the reference
-- It should already be a PRIMARY KEY, but let's ensure it doesn't have other links.
-- (No structural change needed for the column itself, just the constraint removal)

-- 3. Update 'id' to have gen_random_uuid() as default if it's currently relying on auth.users for generation
ALTER TABLE public.institutions 
  ALTER COLUMN id SET DEFAULT gen_random_uuid();

-- 4. Add security columns required for login/auth flow
ALTER TABLE public.institutions
  ADD COLUMN IF NOT EXISTS failed_attempts INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS locked_until TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS refresh_token_hash TEXT;

-- 5. Verify other tables still reference public.institutions(id) correctly
-- No changes needed for programs, institution_details etc. as they reference public.institutions(id)
-- and that column still exists and is still the primary key.

COMMIT;
