-- Consolidated Initial Schema for C2E
-- Date: 2026-02-15

-- 1. Organizations/Institutions
CREATE TABLE IF NOT EXISTS public.institutions (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    institution_name TEXT NOT NULL,
    email TEXT UNIQUE,
    onboarding_status TEXT DEFAULT 'PENDING' CHECK (onboarding_status IN ('PENDING', 'COMPLETED')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 1.1 Detailed Institution Information
CREATE TABLE IF NOT EXISTS public.institution_details (
    institution_id UUID REFERENCES public.institutions(id) ON DELETE CASCADE PRIMARY KEY,
    type TEXT,
    status TEXT DEFAULT 'Autonomous' CHECK (status IN ('Autonomous', 'Non-Autonomous')),
    established_year INTEGER,
    affiliation TEXT,
    address TEXT,
    city TEXT,
    state TEXT,
    country TEXT DEFAULT 'India',
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Academic Programs
CREATE TABLE IF NOT EXISTS public.programs (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    institution_id UUID REFERENCES public.institutions(id) ON DELETE CASCADE NOT NULL,
    program_name TEXT NOT NULL,
    program_code TEXT,
    degree TEXT CHECK (degree IN (
        'B.Tech', 'B.E.', 'M.Tech', 'M.E.', 'MBA', 'MCA', 'B.Sc.', 'M.Sc.', 'B.Com.', 'M.Com.', 'Diploma', 'PhD', 'Integrated', 'B. Tech.', 'B. E.'
    )),
    duration INTEGER,
    level TEXT,
    intake INTEGER,
    academic_year TEXT,
    program_chair TEXT,
    nba_coordinator TEXT,
    vision TEXT,
    mission TEXT,
    stakeholder_feedback_enabled BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Stakeholders
CREATE TABLE IF NOT EXISTS public.stakeholders (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    program_id UUID REFERENCES public.programs(id) ON DELETE CASCADE NOT NULL,
    name TEXT NOT NULL,
    organization TEXT,
    category TEXT NOT NULL CHECK (category IN (
        'Academia', 
        'Industry', 
        'Potential Employers', 
        'Research Organisations', 
        'Professional Body', 
        'Alumni', 
        'Students', 
        'Parents', 
        'Management'
    )),
    contact_no TEXT,
    email TEXT,
    access_token UUID DEFAULT gen_random_uuid(),
    feedback_enabled BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Stakeholder Feedback
CREATE TABLE IF NOT EXISTS public.stakeholder_feedback (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    stakeholder_id UUID REFERENCES public.stakeholders(id) ON DELETE CASCADE NOT NULL,
    program_id UUID REFERENCES public.programs(id) ON DELETE CASCADE NOT NULL,
    expectations TEXT,
    vision_alignment_rating INTEGER,
    feedback_json JSONB,
    submitted_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Program Educational Objectives (PEOs)
CREATE TABLE IF NOT EXISTS public.peos (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    program_id UUID REFERENCES public.programs(id) ON DELETE CASCADE NOT NULL,
    peo_code TEXT NOT NULL, -- e.g., PEO-01
    statement TEXT NOT NULL,
    approved_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. PEO Drafts (Generated by AI)
CREATE TABLE IF NOT EXISTS public.peo_drafts (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    program_id UUID REFERENCES public.programs(id) ON DELETE CASCADE NOT NULL,
    generated_peos JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS POLICIES

-- Institutions
ALTER TABLE public.institutions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Institutions can view their own profile" ON public.institutions FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Institutions can update their own profile" ON public.institutions FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Institutions can insert their profile" ON public.institutions FOR INSERT WITH CHECK (auth.uid() = id);

-- Programs
ALTER TABLE public.programs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Institutions can view their own programs" ON public.programs FOR SELECT USING (auth.uid() = institution_id);
CREATE POLICY "Institutions can insert their own programs" ON public.programs FOR INSERT WITH CHECK (auth.uid() = institution_id);
CREATE POLICY "Institutions can update their own programs" ON public.programs FOR UPDATE USING (auth.uid() = institution_id);
CREATE POLICY "Institutions can delete their own programs" ON public.programs FOR DELETE USING (auth.uid() = institution_id);

-- Stakeholders
ALTER TABLE public.stakeholders ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Institutions can manage their own stakeholders" ON public.stakeholders FOR ALL USING (
    EXISTS (SELECT 1 FROM public.programs WHERE public.programs.id = stakeholders.program_id AND public.programs.institution_id = auth.uid())
);

-- Stakeholder Feedback
ALTER TABLE public.stakeholder_feedback ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Institutions can view feedback for their programs" ON public.stakeholder_feedback FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.programs WHERE public.programs.id = stakeholder_feedback.program_id AND public.programs.institution_id = auth.uid())
);
-- Allow stakeholders to insert feedback if they have a valid token (simplified for now, usually would check token in app logic)
CREATE POLICY "Anyone can insert feedback" ON public.stakeholder_feedback FOR INSERT WITH CHECK (true);

-- PEOs
ALTER TABLE public.peos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Institutions can manage their own PEOs" ON public.peos FOR ALL USING (
    EXISTS (SELECT 1 FROM public.programs WHERE public.programs.id = peos.program_id AND public.programs.institution_id = auth.uid())
);

-- PEO Drafts
ALTER TABLE public.peo_drafts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Institutions can manage their own PEO drafts" ON public.peo_drafts FOR ALL USING (
    EXISTS (SELECT 1 FROM public.programs WHERE public.programs.id = peo_drafts.program_id AND public.programs.institution_id = auth.uid())
);
